name: Build

on: 
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      # Install SWIG and other build tools for Linux
      - name: Install Linux build tools
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y swig build-essential cmake ninja-build

      # Install SWIG on macOS
      - name: Install SWIG on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install swig

      # Install scikit-build and cibuildwheel
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel scikit-build

      # Build wheels
      - name: Build wheels
        uses: pypa/cibuildwheel@3.3.1
        env:
          CIBW_SKIP: pp*
          CIBW_BUILD: "cp314-manylinux_x86_64 cp314-manylinux_aarch64 cp314-win_amd64 cp314-macosx_x86_64 cp314-macosx_arm64"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_ARCHS_WINDOWS: "auto"
          CIBW_ENVIRONMENT_LINUX: "CFLAGS=-fPIC"
          CIBW_ENVIRONMENT_MACOS: "CFLAGS=-fPIC"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  # Build the source distribution under Linux
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout submodule
        run: git submodule update --init py_slvs

      - name: Build source distribution
        run: |
            python -m pip install --upgrade pip setuptools wheel scikit-build
            pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.tar.gz
